---
apiVersion: v1
kind: Namespace
metadata:
  name: fleetlock
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleetlock
  namespace: fleetlock
  labels:
    app.kubernetes.io/name: fleetlock
    app.kubernetes.io/instance: fleetlock
    app.kubernetes.io/version: "latest"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleetlock-config
  namespace: fleetlock
  labels:
    app.kubernetes.io/name: fleetlock
    app.kubernetes.io/instance: fleetlock
    app.kubernetes.io/version: "latest"
data:
  config.yaml: |-
    groups:
      compute:
        slots: 1
      control-plane:
        slots: 1
      default:
        slots: 1
    kubernetes:
      drainRetries: 0
      drainTimeoutSeconds: 300
      kubeconfig: ""
    logLevel: info
    server:
      listen: :8080
      ssl:
        cert: ""
        enabled: false
        key: ""
    storage:
      etcd:
        cert: ""
        endpoints:
        - localhost:2379
        key: ""
        password: ""
        username: ""
      kubernetes:
        namespace: ""
      mongodb:
        database: fleetlock
        url: ""
      mysql:
        address: tcp(localhost:3306)
        database: ""
        options: ""
        password: ""
        username: ""
      postgres:
        address: localhost:26257
        database: ""
        options: ""
        password: ""
        username: ""
      sqlite:
        file: test.db
      type: kubernetes
      valkey:
        addresses:
        - localhost:1234
        db: 0
        password: ""
        sentinel:
          addresses:
          - ""
          enabled: false
          master: ""
          password: ""
          username: ""
        tls: false
        username: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleetlock
  labels:
    app.kubernetes.io/name: fleetlock
    app.kubernetes.io/instance: fleetlock
    app.kubernetes.io/version: "latest"
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleetlock
  labels:
    app.kubernetes.io/name: fleetlock
    app.kubernetes.io/instance: fleetlock
    app.kubernetes.io/version: "latest"
subjects:
  - kind: ServiceAccount
    name: fleetlock
    namespace: fleetlock
roleRef:
  kind: ClusterRole
  name: fleetlock
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleetlock
  namespace: fleetlock
  labels:
    app.kubernetes.io/name: fleetlock
    app.kubernetes.io/instance: fleetlock
    app.kubernetes.io/version: "latest"
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fleetlock
  namespace: fleetlock
  labels:
    app.kubernetes.io/name: fleetlock
    app.kubernetes.io/instance: fleetlock
    app.kubernetes.io/version: "latest"
subjects:
  - kind: ServiceAccount
    name: fleetlock
roleRef:
  kind: Role
  name: fleetlock
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: fleetlock
  namespace: fleetlock
  labels:
    app.kubernetes.io/name: fleetlock
    app.kubernetes.io/instance: fleetlock
    app.kubernetes.io/version: "latest"
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fleetlock
    app.kubernetes.io/instance: fleetlock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetlock
  namespace: fleetlock
  labels:
    app.kubernetes.io/name: fleetlock
    app.kubernetes.io/instance: fleetlock
    app.kubernetes.io/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fleetlock
      app.kubernetes.io/instance: fleetlock
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fleetlock
        app.kubernetes.io/instance: fleetlock
        app.kubernetes.io/version: "latest"
    spec:
      serviceAccountName: fleetlock
      containers:
        - name: fleetlock
          image: "ghcr.io/heathcliff26/fleetlock:latest"
          imagePullPolicy: IfNotPresent
          args:
            - "-c"
            - "/config/config.yaml"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - configMap:
            name: fleetlock-config
          name: config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleetlock
  namespace: fleetlock
  labels:
    app.kubernetes.io/name: fleetlock
    app.kubernetes.io/instance: fleetlock
    app.kubernetes.io/version: "latest"
spec:
  rules:
    - host: "fleetlock.example.org"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fleetlock
                port:
                  name: http
