{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fleetlock.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fleetlock.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fleetlock.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fleetlock.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fleetlock.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "fleetlock.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fleetlock.fullname" . }}
  labels:
    {{- include "fleetlock.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fleetlock.fullname" . }}
  labels:
    {{- include "fleetlock.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fleetlock.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "fleetlock.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
